version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: backyard-db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=backyard_db
      - POSTGRES_USER=backyard_user
      - POSTGRES_PASSWORD=backyard_pass
    ports:
      - "5432:5432"

  backend:
    build: .
    container_name: backyard-backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - DATABASE=postgres
      - SQL_HOST=db
      - SQL_PORT=5432
      - DATABASE_URL=postgres://backyard_user:backyard_pass@db:5432/backyard_db
      - EMAIL_HOST=mailpit
      - EMAIL_PORT=1025
    depends_on:
      - db
      - mailpit

  worker:
    build: .
    container_name: backyard-worker
    command: >
      sh -c "while true; do 
        python manage.py limpiar_reservas; 
        sleep 60; 
      done"
    env_file:
      - .env
    environment:
      - DATABASE=postgres
      - SQL_HOST=db
      - SQL_PORT=5432
      - DATABASE_URL=postgres://backyard_user:backyard_pass@db:5432/backyard_db
    depends_on:
      - db
    restart: always

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
      args:
        - VITE_API_URL=${VITE_API_URL:-http://localhost:8000}
    container_name: backyard-frontend
    ports:
      - "80:80"
    # El resto se mantiene igual
    depends_on:
      - backend

  mailpit:
    image: axllent/mailpit
    container_name: backyard-mailpit
    ports:
      - "8025:8025" # Interfaz Web
      - "1025:1025" # Servidor SMTP
    restart: always

volumes:
  postgres_data:
