version: '3.8'

services:
  mailpit:
    image: axllent/mailpit
    container_name: backyard-mailpit
    ports:
      - "8025:8025" # Interfaz Web
      - "1025:1025" # Servidor SMTP
    restart: always
